### ISSUE TITLE
{"context": "client"} Invalid Session Properties requested

### ISSUE THREAD

**Issue by dohainamhn** [WalletConnect/web3modal-react-native#39] opened 2023-05-26 16:17 UTC
Error when trying to send sign request on Trust Wallet:

![Screenshot from 2023-05-26 23-11-39](https://github.com/WalletConnect/web3modal-react-native/assets/60875054/f9f07ee3-b1ac-41cb-8124-60ae89864dcc)

{"context": "client"} Invalid Session Properties requested

@web3modal/react-native version: 1.0.0-alpha.5
OS:  android  11 
device: simulator

**Comment by finessevanes** [comment] 2023-05-26 18:29
Hey - thanks for reporting. I believe this is a known issue, but let me follow up with the Trust team.

**Comment by ignaciosantise** [comment] 2023-05-27 16:42
@dohainamhn are you using custom `sessionParams`? if so, can you upload them?

**Comment by dohainamhn** [comment] 2023-05-27 17:27
yeah sure
![Screenshot from 2023-05-28 00-26-33](https://github.com/WalletConnect/web3modal-react-native/assets/60875054/6ccf0935-b9ab-400b-959c-1fa445ed5eff)

**Comment by ignaciosantise** [comment] 2023-05-29 15:24
@dohainamhn can you provide more info to reproduce the issue?

1. Steps to follow after opening the app
2. Selected wallet
3. Video if possible

**Comment by ThakerJayam** [comment] 2023-06-09 23:55
I am having similar issue using react on Android wth TrustWallet.

**Comment by ignaciosantise** [comment] 2023-06-21 16:13
Closing this as we couldn't reproduce it. I'll reopen it if clear steps to reproduce are provided

**Closed** 2023-06-21 16:13 UTC
