### ISSUE TITLE
[bug] IOS Crashes When Using this package with Webview

### ISSUE THREAD

**Issue by Martin2037** [WalletConnect/web3modal-react-native#150] opened 2024-02-29 09:44 UTC
### Description

**Environment:**

IOS version: 17.2
Simulator: iPhone 15 Pro
React-Native version: 0.73.5 (new architecture)

**Description:**

The application crashes without any error messages when I click the connect button after installing both the Wallet-Connect and react-native-webview packages. The application compiles without any errors.
xcode stack👇
![e74b3cd0-1ed8-4153-9714-359fa0dead23](https://github.com/WalletConnect/web3modal-react-native/assets/63692237/58d6c7d6-70cb-4654-83ee-c0da29320050)

**Actual behavior:**
The application crashes without any error messages.

**Minimal Reproduction:**

I've created a minimal reproduction of this issue. The repository can be found at: [https://github.com/Martin2037/rn-modal-crash](wallet-connect-crashed)

### Web3Modal SDK version

@web3modal/wagmi-react-native 1.2.0

### Output of `npx react-native info`

System:
  OS: macOS 14.2.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 69.55 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.9.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.4.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/zhujunyang/.rubies/ruby-3.3.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /Users/zhujunyang/.rubies/ruby-3.3.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.5
    wanted: 0.73.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Steps to reproduce

1、Install both wallet-connect and webview packages.
2、Compile the application
3、Click the connect button.

### Snack, code example, screenshot, or link to a repository

[https://github.com/Martin2037/rn-modal-crash](wallet-connect-crashed)

**Comment by opensourcex123** [comment] 2024-02-29 09:46
same issue here

**Comment by Martin2037** [comment] 2024-03-01 02:31
@ignaciosantise

**Comment by Martin2037** [comment] 2024-03-02 08:03
need help plz

**Comment by Martin2037** [comment] 2024-03-02 09:46
update: 
using **react-native-actions-sheet** cause the same problem

**Comment by ignaciosantise** [comment] 2024-03-04 15:17
@Martin2037 hey, i wasn't able to reproduce the issue with your repository. It seems more of an issue either with the other libs or with your current setup. Can you expand the info about the error?

https://github.com/WalletConnect/web3modal-react-native/assets/25931366/2ad91576-3ba9-42f8-94e4-8d25562d469b

**Comment by Martin2037** [comment] 2024-03-05 03:19
> @Martin2037 hey, i wasn't able to reproduce the issue with your repository. It seems more of an issue either with the other libs or with your current setup. Can you expand the info about the error?
> 
>  simulator.mp4

try to run:
**RCT_NEW_ARCH_ENABLED=1 bundle exec pod install**

crashed with new arch

**Comment by Martin2037** [comment] 2024-03-05 10:14
@ignaciosantise

**Comment by ignaciosantise** [comment] 2024-03-05 14:26
@Martin2037 i was able to reproduce the error, but it seems the crash is related with `react-native-webview`, apparently it doesn't work well with modals. If i remove the webview package, both web3modal sdk and actions-sheet work properly.

Someone opened this issue: https://github.com/react-native-webview/react-native-webview/issues/3336 and you also added your +1 there. 

Im closing this as the issue is not from our SDK.

**Closed by ignaciosantise** 2024-03-05 14:26 UTC
Labels: bug, question
