### ISSUE TITLE
Failed to decrypt error

### ISSUE THREAD

**Issue by Mostafatalaat770** [WalletConnect/web3modal-react-native#22] opened 2023-05-10 10:29 UTC
Using this snippet while connected to trust wallet
https://github.com/WalletConnect/web3modal-react-native/blob/388090a82e99b3e4cfe6a7b149c1e10ab2fc228a/example/src/utils/MethodUtil.ts#L41-L48

causes `failed to decrypt` error, but I found something interesting when opened the wallet provider app this happens:
![image](https://user-images.githubusercontent.com/47927436/236448273-b3d1e9bd-cafe-4eee-82ad-1cc4978c9bfa.png)
I added a log when it enters `onSessionDelete` in `useConfigure` hook, and as you see the sessions are not in sync or something is not right. the first one is from the event and the second is from the `clientCtrl`.

and it shows to sign the message normally, but on accepting, it throws the `failed to decrypt` error, so most probably it's a wallet connect issue than a modal issue, what do you think?

_Originally posted by @Mostafatalaat770 in https://github.com/WalletConnect/web3modal-react-native/issues/13#issuecomment-1536137085_

**Comment by StevenBarnett1** [comment] 2023-05-11 19:08
Same here!

**Comment by finessevanes** [comment] 2023-05-12 05:26
Your comment has been viewed and shared with our development team for review.

**Comment by ignaciosantise** [comment] 2023-05-23 14:48
Update on this issue: we reached Trust Wallet team and apparently the issue will be solved in their next release, that is currently in Apple's review. Let's wait for that release 💪

**Comment by ignaciosantise** [comment] 2023-06-08 12:54
hey @StevenBarnett1 no updates yet 👎 We reached Trust team again yesterday

**Comment by boulinb** [comment] 2023-06-20 08:32
Hey @ignaciosantise ! 

Has the TrustWallet team given you a date for resolving the bug?

**Comment by ignaciosantise** [comment] 2023-06-20 16:36
hey @boulinb, they didn't provide an estimated time, but i tested their latest version in TestFlight and the problem is solved 🤝

**Comment by boulinb** [comment] 2023-06-20 17:09
> hey @boulinb, they didn't provide an estimated time, but i tested their latest version in TestFlight and the problem is solved 🤝

That's great news! Can't wait for them to go into production!

**Comment by ignaciosantise** [comment] 2023-06-21 12:41
@boulinb Trust Wallet v8.9 is now available 🎉  Can you confirm the issue is solved on your side?

**Comment by ignaciosantise** [comment] 2023-06-21 16:15
Great! Im closing this issue as it is solved in latest Trust Wallet version (v8.9 in iOS)

**Closed by ignaciosantise** 2023-06-21 16:15 UTC
